---
ops: [analyze]
model: {
    path: /mnt/sdceph/users/humanbase/prod/humanbase-data/data/deepsea/models/sei_torch.py,
    class: Sei,
    class_args: {
    },
    non_strand_specific: mean
}
analyze_sequences: !obj:selene_sdk.predict.AnalyzeSequences {
    sequence_length: 4096,
    batch_size: 128,
    use_cuda: True,
    trained_model_path: /mnt/sdceph/users/humanbase/prod/humanbase-data/data/deepsea/models/sei.pth,
    reference_sequence: !obj:selene_sdk.sequences.Genome {
        input_path: /mnt/sdceph/users/humanbase/prod/humanbase-data/data/deepsea/genome/hg38_UCSC.fa,
    },
    features: !obj:selene_sdk.utils.load_features_list {
        input_path: /mnt/sdceph/users/humanbase/prod/humanbase-data/data/deepsea/models/sei_features.txt
    },
    write_mem_limit: 5000
}
prediction: {
    input_path: /mnt/sdceph/users/humanbase/prod/media/7ac45b4c-94d8-4da4-aa1a-06569dd9c2e7_fasta_hg38_centeratpeak_4096bp_addin3bp.fasta,
    output_dir: /mnt/sdceph/users/humanbase/prod/media/,
    output_format: tsv,
}
random_seed: 1337
...
